// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4EbRTaz52zQJr-R4qlE4u-F8W2DYhBE',
    appId: '1:552969174887:web:49ae223e7cd2613f1b79c2',
    messagingSenderId: '552969174887',
    projectId: 'registration-form-bc8e6',
    authDomain: 'registration-form-bc8e6.firebaseapp.com',
    storageBucket: 'registration-form-bc8e6.firebasestorage.app',
    measurementId: 'G-2GJZWKB8WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSv_JICvs84evw36CfPm8qL22yI9Jfdk',
    appId: '1:552969174887:android:2033c1671ab851db1b79c2',
    messagingSenderId: '552969174887',
    projectId: 'registration-form-bc8e6',
    storageBucket: 'registration-form-bc8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48OZbj_mw9MXq76f3CgPFGaX8DhelWUo',
    appId: '1:552969174887:ios:b6941cfe6d31ab3c1b79c2',
    messagingSenderId: '552969174887',
    projectId: 'registration-form-bc8e6',
    storageBucket: 'registration-form-bc8e6.firebasestorage.app',
    iosBundleId: 'com.cherry.registrationform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48OZbj_mw9MXq76f3CgPFGaX8DhelWUo',
    appId: '1:552969174887:ios:b6941cfe6d31ab3c1b79c2',
    messagingSenderId: '552969174887',
    projectId: 'registration-form-bc8e6',
    storageBucket: 'registration-form-bc8e6.firebasestorage.app',
    iosBundleId: 'com.cherry.registrationform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG4EbRTaz52zQJr-R4qlE4u-F8W2DYhBE',
    appId: '1:552969174887:web:3c8bb9bdeac8f3101b79c2',
    messagingSenderId: '552969174887',
    projectId: 'registration-form-bc8e6',
    authDomain: 'registration-form-bc8e6.firebaseapp.com',
    storageBucket: 'registration-form-bc8e6.firebasestorage.app',
    measurementId: 'G-KSMGQCVV8N',
  );
}
